export const CARD_NAMES = {
    'BALOON_DOG': 'baloon-dog',
    'BIKE': 'bike',
    'CANDIES': 'candies',
    'CHILDREN': 'children',
    'COVER': 'cover',
    'CRAYON': 'crayon',
    'DINOSAUR': 'dinosaur',
    'FATHER': 'father',
    'HAND': 'hand',
    'HEART': 'heart',
    'LOVE': 'love',
    'MOTHERS_DAY': 'mothers-day',
    'PLAYGROUND': 'playground',
    'PLAYTIME': 'playtime',
    'PUZZLE': 'puzzle',
    'RAINBOW': 'rainbow',
    'ROCKING_HORSE': 'rocking-horse',
    'SANDBOX': 'sandbox',
    'WINDMILL': 'windmill',
}